/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: LowlyPoly (https://sketchfab.com/lowlypoly)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stylized-crystal-0a0c75dab0844e7fa5b299d4af858bec
Title: Stylized Crystal
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model3d(props) {
  const { nodes, materials } = useGLTF('/stylized_crystal.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.crystal17_2_crystal_17_2_0.geometry}
        material={materials.crystal_17_2}
        position={[-20, -208.492, -85]}
        scale={99.987}
      />
    </group>
  )
}

useGLTF.preload('/stylized_crystal.glb')